# ansible-k8s/inventory/hosts.yml

all:
  children:
    control_plane:
      hosts:
        ansibleCplane:
          ansible_host: 10.110.188.85
          ansible_user: ansiblecplane

    workers:
      hosts:
        ansibleWorker1:
          ansible_host: 10.110.188.86
          ansible_user: ansibleworker1        # ← adjust to actual username

        ansibleWorker2:                       # ← NEW — second worker
          ansible_host: 10.110.188.87
          ansible_user: ansibleworker2

  vars:
    ansible_python_interpreter: /usr/bin/python3
