"""
routes/configure.py — Phase 3

Generates inventory.ini and group_vars/all.yml from dashboard inputs.
No Ansible project file is ever modified.
All output goes to generated/ which is git-ignored.
"""
from typing import List

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from core.paths import SSH_KEY_PATH, INVENTORY_PATH, VARS_PATH

router = APIRouter()


# ── Models ─────────────────────────────────────────────────────────────────────

class WorkerNode(BaseModel):
    ip: str
    hostname: str
    ssh_user: str


class ControlPlane(BaseModel):
    ip: str
    hostname: str
    ssh_user: str


class ClusterConfig(BaseModel):
    control_plane: ControlPlane
    workers: List[WorkerNode]
    kubernetes_version: str = "1.30.5"
    containerd_version: str = "1.7.22"
    calico_version: str     = "v3.28.2"
    longhorn_version: str   = "1.7.2"
    pod_cidr: str           = "192.168.0.0/16"
    service_cidr: str       = "10.96.0.0/12"
    cluster_name: str       = "k8s-cluster"
    deploy_longhorn: bool   = True


# ── Replica logic ──────────────────────────────────────────────────────────────

def _replica_settings(worker_count: int) -> tuple:
    """
    Derive Longhorn replica count and soft anti-affinity from worker count.

    1 worker  → replica 1, soft_anti true  (only one node available)
    2 workers → replica 2, soft_anti false (one replica per worker)
    3+        → replica 3, soft_anti false (Longhorn recommended max)
    """
    if worker_count == 1:
        return 1, "true"
    elif worker_count == 2:
        return 2, "false"
    else:
        return 3, "false"


# ── File generators ────────────────────────────────────────────────────────────

def _make_inventory(config: ClusterConfig) -> str:
    cp = config.control_plane
    lines = [
        "[control_plane]",
        f"{cp.hostname} ansible_host={cp.ip} ansible_user={cp.ssh_user}",
        "",
        "[workers]",
    ]
    for w in config.workers:
        lines.append(
            f"{w.hostname} ansible_host={w.ip} ansible_user={w.ssh_user}"
        )
    lines += [
        "",
        "[all:vars]",
        "ansible_python_interpreter=/usr/bin/python3",
        f"ansible_ssh_private_key_file={SSH_KEY_PATH}",
    ]
    return "\n".join(lines) + "\n"


def _make_group_vars(config: ClusterConfig) -> str:
    cp = config.control_plane
    replica_count, soft_anti = _replica_settings(len(config.workers))

    hosts = [f"  - {{ name: {cp.hostname}, ip: \"{cp.ip}\" }}"]
    for w in config.workers:
        hosts.append(f"  - {{ name: {w.hostname}, ip: \"{w.ip}\" }}")

    return f"""# Generated by k8s-launcher — do not edit manually

# ── Kubernetes ─────────────────────────────────────────────────────────────────
kubernetes_version: "{config.kubernetes_version}"
containerd_version: "{config.containerd_version}"
calico_version:     "{ ("v" + config.calico_version) if not config.calico_version.startswith("v") else config.calico_version }"

# ── Control plane ──────────────────────────────────────────────────────────────
cp_hostname: "{cp.hostname}"
cp_ip:       "{cp.ip}"

# ── Networking ─────────────────────────────────────────────────────────────────
pod_cidr:     "{config.pod_cidr}"
service_cidr: "{config.service_cidr}"
cluster_name: "{config.cluster_name}"

# ── Hosts entries (written to /etc/hosts on all nodes) ─────────────────────────
cluster_hosts:
{chr(10).join(hosts)}

# ── Artifact directory ─────────────────────────────────────────────────────────
artifacts_dir: "/home/{cp.ssh_user}/cluster-artifacts"

# ── Longhorn ───────────────────────────────────────────────────────────────────
longhorn_version:                    "{config.longhorn_version}"
longhorn_namespace:                  "longhorn-system"
longhorn_replica_count:              {replica_count}
longhorn_replica_soft_anti_affinity: "{soft_anti}"
longhorn_data_path:                  "/var/lib/longhorn"
longhorn_storageclass_name:          "longhorn-jupyterhomes"
longhorn_storageclass_default:       "true"
longhorn_reclaim_policy:             "Retain"
longhorn_over_provisioning_pct:      150
longhorn_min_available_pct:          25
longhorn_node_drain_policy:          "block-if-contains-last-replica"
longhorn_artifacts_dir:              "/home/{cp.ssh_user}/cluster-artifacts/longhorn"
"""


# ── Endpoints ──────────────────────────────────────────────────────────────────

@router.post("/api/configure")
async def configure(config: ClusterConfig):
    """
    Generate inventory.ini and group_vars/all.yml from cluster config.
    Files are written to generated/ (git-ignored).
    """
    INVENTORY_PATH.write_text(_make_inventory(config))
    VARS_PATH.write_text(_make_group_vars(config))

    replica_count, soft_anti = _replica_settings(len(config.workers))

    return {
        "status": "ok",
        "files": {
            "inventory":   str(INVENTORY_PATH),
            "group_vars":  str(VARS_PATH)
        },
        "derived": {
            "worker_count":                      len(config.workers),
            "longhorn_replica_count":            replica_count,
            "longhorn_replica_soft_anti_affinity": soft_anti
        }
    }


@router.get("/api/configure/preview")
async def preview_files():
    """
    Return current content of both generated files.
    Used by dashboard to show what was generated before deploying.
    """
    if not INVENTORY_PATH.exists() or not VARS_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="No generated files found. Run POST /api/configure first."
        )
    return {
        "inventory":  INVENTORY_PATH.read_text(),
        "group_vars": VARS_PATH.read_text()
    }


@router.get("/api/compat-matrix")
async def get_compat_matrix():
    """
    Return the full compat_matrix.json content.
    Used by the dashboard to load compatibility rules dynamically.
    """
    import json
    from core.paths import COMPAT_MATRIX_PATH
    if not COMPAT_MATRIX_PATH.exists():
        raise HTTPException(status_code=404, detail="compat_matrix.json not found")
    return json.loads(COMPAT_MATRIX_PATH.read_text())


@router.get("/api/compat-matrix")
async def get_compat_matrix():
    import json
    from core.paths import COMPAT_MATRIX_PATH
    if not COMPAT_MATRIX_PATH.exists():
        raise HTTPException(status_code=404, detail="compat_matrix.json not found")
    return json.loads(COMPAT_MATRIX_PATH.read_text())
