"""
routes/configure.py — Phase 3

Generates inventory.ini and group_vars/all.yml from dashboard inputs.
Also wires up passwordless SSH from control plane to all worker nodes
so Ansible delegate_to tasks and cross-node operations never prompt.
Also writes ansible.cfg to every Ansible project on every configure run
so StrictHostKeyChecking=no is always guaranteed regardless of prior state.
No Ansible project file is ever modified beyond ansible.cfg.
All output goes to generated/ which is git-ignored.
"""
import json
import subprocess
from pathlib import Path
from typing import List

import paramiko
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from core.paths import SSH_KEY_PATH, SSH_PUB_KEY_PATH, INVENTORY_PATH, VARS_PATH, COMPAT_MATRIX_PATH
from core.ssh import get_client_with_key, run_command

router = APIRouter()


# ── Models ─────────────────────────────────────────────────────────────────────

class WorkerNode(BaseModel):
    ip: str
    hostname: str
    ssh_user: str


class ControlPlane(BaseModel):
    ip: str
    hostname: str
    ssh_user: str


class ClusterConfig(BaseModel):
    control_plane: ControlPlane
    workers: List[WorkerNode]
    kubernetes_version: str = "1.30.5"
    containerd_version: str = "1.7.22"
    calico_version: str     = "v3.28.2"
    longhorn_version: str   = "1.7.2"
    pod_cidr: str           = "192.168.0.0/16"
    service_cidr: str       = "10.96.0.0/12"
    cluster_name: str       = "k8s-cluster"


# ── Replica logic ──────────────────────────────────────────────────────────────

def _replica_settings(worker_count: int) -> tuple:
    if worker_count == 1:
        return 1, "true"
    elif worker_count == 2:
        return 2, "false"
    else:
        return 3, "false"


# ── File generators ────────────────────────────────────────────────────────────

def _make_inventory(config: ClusterConfig) -> str:
    cp = config.control_plane
    lines = [
        "[control_plane]",
        f"{cp.hostname} ansible_host={cp.ip} ansible_user={cp.ssh_user}",
        "",
        "[workers]",
    ]
    for w in config.workers:
        lines.append(f"{w.hostname} ansible_host={w.ip} ansible_user={w.ssh_user}")
    lines += [
        "",
        "[all:vars]",
        "ansible_python_interpreter=/usr/bin/python3",
        f"ansible_ssh_private_key_file={SSH_KEY_PATH}",
    ]
    return "\n".join(lines) + "\n"


def _make_group_vars(config: ClusterConfig) -> str:
    cp = config.control_plane
    replica_count, soft_anti = _replica_settings(len(config.workers))

    hosts = [f"  - {{ name: {cp.hostname}, ip: \"{cp.ip}\" }}"]
    for w in config.workers:
        hosts.append(f"  - {{ name: {w.hostname}, ip: \"{w.ip}\" }}")

    calico = config.calico_version
    if not calico.startswith("v"):
        calico = "v" + calico

    return f"""# Generated by k8s-launcher — do not edit manually

# ── Kubernetes ─────────────────────────────────────────────────────────────────
kubernetes_version: "{config.kubernetes_version}"
containerd_version: "{config.containerd_version}"
calico_version:     "{calico}"

# ── Control plane ──────────────────────────────────────────────────────────────
cp_hostname: "{cp.hostname}"
cp_ip:       "{cp.ip}"

# ── Networking ─────────────────────────────────────────────────────────────────
pod_cidr:     "{config.pod_cidr}"
service_cidr: "{config.service_cidr}"
cluster_name: "{config.cluster_name}"

# ── Hosts entries ──────────────────────────────────────────────────────────────
cluster_hosts:
{chr(10).join(hosts)}

# ── Artifact directory ─────────────────────────────────────────────────────────
artifacts_dir: "/home/{cp.ssh_user}/cluster-artifacts"

# ── Longhorn ───────────────────────────────────────────────────────────────────
longhorn_version:                    "{config.longhorn_version}"
longhorn_namespace:                  "longhorn-system"
longhorn_replica_count:              {replica_count}
longhorn_replica_soft_anti_affinity: "{soft_anti}"
longhorn_data_path:                  "/var/lib/longhorn"
longhorn_storageclass_name:          "longhorn-jupyterhomes"
longhorn_storageclass_default:       "true"
longhorn_reclaim_policy:             "Retain"
longhorn_over_provisioning_pct:      150
longhorn_min_available_pct:          25
longhorn_node_drain_policy:          "block-if-contains-last-replica"
longhorn_artifacts_dir:              "/home/{cp.ssh_user}/cluster-artifacts/longhorn"
"""


# ── Write ansible.cfg to every Ansible project ────────────────────────────────
# Always overwrites — never skips — so StrictHostKeyChecking=no is guaranteed
# on every configure run regardless of what was there before.
# This is the automatic fix for the OpenSSH fingerprint prompt that fires
# when Ansible encounters a node not yet in known_hosts.

_ANSIBLE_CFG_CONTENT = """\
[defaults]
host_key_checking = False
stdout_callback   = yaml
timeout           = 30

[ssh_connection]
ssh_args   = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no
pipelining = True
"""

_ANSIBLE_PROJECT_DIRS = [
    Path("~/k8s-launcher/ansible-k8s").expanduser(),
    Path("~/k8s-launcher/ansible-longhorn").expanduser(),
    Path("~/k8s-launcher/ansible-monitoring").expanduser(),
    Path("~/k8s-launcher/ansible-dashboard").expanduser(),
    Path("~/k8s-launcher/ansible-gitlab").expanduser(),
    Path("~/k8s-launcher/ansible-jupyterhub").expanduser(),
    Path("~/k8s-launcher/ansible-kyverno").expanduser(),
    Path("~/k8s-launcher/ansible-workers").expanduser(),
    Path("~/k8s-launcher/ansible-reset").expanduser(),
]

def _write_ansible_cfgs() -> list:
    written = []
    for project_dir in _ANSIBLE_PROJECT_DIRS:
        if not project_dir.exists():
            continue
        cfg_path = project_dir / "ansible.cfg"
        cfg_path.write_text(_ANSIBLE_CFG_CONTENT)
        written.append(str(cfg_path))
    return written


# ── Wire cplane → workers passwordless SSH ────────────────────────────────────
# Triggered automatically during configure so that by the time any playbook
# runs, the control plane can already SSH into every worker without prompting.
#
# Steps (all using controller's private key — no passwords needed here because
# bootstrap already pushed the controller pubkey to every node):
#   1. SSH into cplane, generate ed25519 keypair if missing
#   2. Read cplane's public key
#   3. For each worker: append cplane pubkey to worker's authorized_keys
#   4. On cplane: run ssh-keyscan for each worker → populate cplane known_hosts

def _wire_cplane_to_workers(cp: ControlPlane, workers: List[WorkerNode]) -> dict:
    if not workers:
        return {"status": "skipped", "message": "No workers to wire"}

    report = {"cplane_keygen": None, "workers": []}

    # ── Step 1 & 2 — generate cplane keypair if missing, read pubkey ──────────
    cp_client = None
    try:
        cp_client = get_client_with_key(cp.ip, cp.ssh_user, str(SSH_KEY_PATH))

        _, _, rc = run_command(cp_client, "test -f ~/.ssh/id_ed25519.pub")
        if rc != 0:
            _, stderr, rc = run_command(
                cp_client,
                "ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N '' -q"
            )
            if rc != 0:
                return {
                    "status":  "error",
                    "message": f"cplane keypair generation failed: {stderr}"
                }
            report["cplane_keygen"] = "generated"
        else:
            report["cplane_keygen"] = "already exists"

        cplane_pubkey, _, rc = run_command(cp_client, "cat ~/.ssh/id_ed25519.pub")
        if rc != 0 or not cplane_pubkey.strip():
            return {"status": "error", "message": "Could not read cplane public key"}
        cplane_pubkey = cplane_pubkey.strip()

    except Exception as exc:
        return {"status": "error", "message": f"Cannot reach cplane: {exc}"}
    finally:
        if cp_client:
            cp_client.close()

    # ── Step 3 — push cplane pubkey to each worker ────────────────────────────
    for worker in workers:
        w_client = None
        try:
            w_client = get_client_with_key(worker.ip, worker.ssh_user, str(SSH_KEY_PATH))

            cmds = [
                "mkdir -p ~/.ssh",
                "chmod 700 ~/.ssh",
                f"echo '{cplane_pubkey}' >> ~/.ssh/authorized_keys",
                "sort -u ~/.ssh/authorized_keys -o ~/.ssh/authorized_keys",
                "chmod 600 ~/.ssh/authorized_keys",
            ]
            for cmd in cmds:
                _, stderr, exit_code = run_command(w_client, cmd)
                if exit_code != 0:
                    report["workers"].append({
                        "ip":     worker.ip,
                        "status": "error",
                        "message": f"Command failed: {cmd} — {stderr}"
                    })
                    break
            else:
                report["workers"].append({
                    "ip":     worker.ip,
                    "status": "ok",
                    "message": "cplane pubkey pushed"
                })

        except Exception as exc:
            report["workers"].append({
                "ip":     worker.ip,
                "status": "error",
                "message": f"Cannot reach worker: {exc}"
            })
        finally:
            if w_client:
                w_client.close()

    # ── Step 4 — populate cplane known_hosts for all workers ──────────────────
    cp_client = None
    try:
        cp_client = get_client_with_key(cp.ip, cp.ssh_user, str(SSH_KEY_PATH))

        for worker in workers:
            scan_out, _, _ = run_command(
                cp_client,
                f"ssh-keyscan -H -T 5 {worker.ip} 2>/dev/null"
            )
            if scan_out.strip():
                run_command(
                    cp_client,
                    f"touch ~/.ssh/known_hosts && "
                    f"echo '{scan_out.strip()}' >> ~/.ssh/known_hosts"
                )

        run_command(
            cp_client,
            "sort -u ~/.ssh/known_hosts -o ~/.ssh/known_hosts"
        )

    except Exception as exc:
        report["known_hosts_warning"] = f"cplane known_hosts population failed: {exc}"
    finally:
        if cp_client:
            cp_client.close()

    failed = [w for w in report["workers"] if w["status"] == "error"]
    report["status"] = "error" if failed else "ok"
    return report


# ── Endpoints ──────────────────────────────────────────────────────────────────

@router.post("/api/configure")
async def configure(config: ClusterConfig):
    INVENTORY_PATH.write_text(_make_inventory(config))
    VARS_PATH.write_text(_make_group_vars(config))
    replica_count, soft_anti = _replica_settings(len(config.workers))

    # Always write ansible.cfg to all projects — guarantees no fingerprint prompts
    cfgs_written = _write_ansible_cfgs()

    # Wire cplane → workers passwordless SSH automatically
    wire_report = _wire_cplane_to_workers(config.control_plane, config.workers)

    return {
        "status": "ok",
        "files": {
            "inventory":  str(INVENTORY_PATH),
            "group_vars": str(VARS_PATH)
        },
        "derived": {
            "worker_count":                        len(config.workers),
            "longhorn_replica_count":              replica_count,
            "longhorn_replica_soft_anti_affinity": soft_anti
        },
        "ansible_cfgs_written": cfgs_written,
        "cplane_to_workers":    wire_report
    }


@router.get("/api/configure/preview")
async def preview_files():
    if not INVENTORY_PATH.exists() or not VARS_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="No generated files found. Run POST /api/configure first."
        )
    return {
        "inventory":  INVENTORY_PATH.read_text(),
        "group_vars": VARS_PATH.read_text()
    }


@router.get("/api/compat-matrix")
async def get_compat_matrix():
    if not COMPAT_MATRIX_PATH.exists():
        raise HTTPException(status_code=404, detail="compat_matrix.json not found")
    return json.loads(COMPAT_MATRIX_PATH.read_text())
