"""
routes/dashboard_deploy.py — Admin Dashboard tab
"""
import json
import subprocess

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from core.paths import (
    ANSIBLE_DASHBOARD_DIR,
    INVENTORY_PATH,
    VARS_PATH,
    GITLAB_OUTPUTS_PATH,
    GENERATED_DIR,
    DASHBOARD_VARS_PATH,
)

router = APIRouter()


class DashboardConfig(BaseModel):
    http_pass:   str
    port:        int = 8888
    repo:        str = "https://github.com/sambett/k8s-launcher.git"


@router.get("/api/dashboard/status")
async def dashboard_status():
    return {"configured": DASHBOARD_VARS_PATH.exists()}


@router.post("/api/dashboard/configure")
async def dashboard_configure(cfg: DashboardConfig):
    if not GITLAB_OUTPUTS_PATH.exists():
        return {"status": "error",
                "message": "gitlab-outputs.json not found — run GitLab tab first."}
    if not VARS_PATH.exists():
        return {"status": "error",
                "message": "Cluster vars not found — run Configure tab first."}

    gl           = json.loads(GITLAB_OUTPUTS_PATH.read_text())
    secrets_path = GENERATED_DIR / "secrets.env"

    admin_token = ""
    if secrets_path.exists():
        for line in secrets_path.read_text().splitlines():
            if line.startswith("GITLAB_TOKEN="):
                admin_token = line.split("=", 1)[1].strip()
    if not admin_token:
        admin_token = gl.get("admin_token", "")

    cp_user = ""
    if INVENTORY_PATH.exists():
        for line in INVENTORY_PATH.read_text().splitlines():
            if "ansible_user=" in line and "[" not in line:
                for part in line.split():
                    if part.startswith("ansible_user="):
                        cp_user = part.split("=", 1)[1]
                        break
                break

    registry_host = gl.get("gitlab_registry_host", "")
    registry_ns   = gl.get("registry_namespace", "registry/notebook-images")
    gitlab_url    = gl.get("gitlab_url", "")
    project_id    = gl.get("notebook_images_project_id", "1")

    content = (
        f"# Generated by k8s-launcher — do not edit manually\n\n"
        f"dashboard_user:          \"{cp_user}\"\n"
        f"dashboard_http_user:     \"admin\"\n"
        f"dashboard_http_pass:     \"{cfg.http_pass}\"\n"
        f"dashboard_gitlab_token:  \"{admin_token}\"\n"
        f"dashboard_port:          {cfg.port}\n"
        f"workbench_repo:          \"{cfg.repo}\"\n"
        f"jhub_gitlab_url:         \"{gitlab_url}\"\n"
        f"jhub_registry_host:      \"{registry_host}\"\n"
        f"jhub_registry_namespace: \"{registry_ns}\"\n"
        f"notebook_images_project_id: {project_id}\n"
    )

    DASHBOARD_VARS_PATH.write_text(content)
    return {"status": "ok"}


def _dashboard_stream():
    if not INVENTORY_PATH.exists():
        yield "data: __ERROR__:no_inventory\n\n"
        return
    if not DASHBOARD_VARS_PATH.exists():
        yield "data: __ERROR__:no_dashboard_vars — run Generate config first\n\n"
        return

    process = subprocess.Popen(
        ["ansible-playbook",
         "-i", str(INVENTORY_PATH),
         "site.yml",
         "--extra-vars", f"@{VARS_PATH}",
         "--extra-vars", f"@{DASHBOARD_VARS_PATH}"],
        cwd=str(ANSIBLE_DASHBOARD_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    for line in iter(process.stdout.readline, ""):
        stripped = line.rstrip()
        if stripped:
            yield f"data: {stripped}\n\n"

    process.stdout.close()
    process.wait()

    if process.returncode == 0:
        yield "data: __DONE__\n\n"
    else:
        yield f"data: __ERROR__:{process.returncode}\n\n"


@router.get("/api/dashboard/stream")
async def dashboard_deploy_stream():
    return StreamingResponse(
        _dashboard_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
