"""
routes/jupyterhub.py — JupyterHub tab
Reads credentials from gitlab-outputs.json automatically.
User only needs to provide nodeport.
"""
import json
import re
import secrets
import subprocess

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from core.paths import (
    ANSIBLE_JUPYTERHUB_DIR,
    INVENTORY_PATH,
    VARS_PATH,
    GITLAB_OUTPUTS_PATH,
    GITLAB_VARS_PATH,
    JUPYTERHUB_VARS_PATH,
    GENERATED_DIR,
)

router = APIRouter()


class JupyterHubConfig(BaseModel):
    nodeport:        int    = 32080
    storage_class:   str    = "longhorn-jupyterhomes"
    user_storage:    str    = "10Gi"


@router.get("/api/jupyterhub/prefill")
async def jupyterhub_prefill():
    if not GITLAB_OUTPUTS_PATH.exists():
        return {"status": "not_found", "message": "Run the GitLab tab first."}
    data = json.loads(GITLAB_OUTPUTS_PATH.read_text())
    return {
        "status":             "ok",
        "gitlab_url":         data.get("gitlab_url"),
        "registry_host":      data.get("gitlab_registry_host"),
        "registry_namespace": data.get("registry_namespace"),
        "oauth_client_id":    data.get("oauth_client_id"),
        "deploy_token_user":  data.get("registry_deploy_token_user"),
    }


@router.post("/api/jupyterhub/configure")
async def jupyterhub_configure(cfg: JupyterHubConfig):
    if not GITLAB_OUTPUTS_PATH.exists():
        return {"status": "error",
                "message": "gitlab-outputs.json not found — run GitLab tab first."}
    if not VARS_PATH.exists():
        return {"status": "error",
                "message": "Cluster vars not found — run Configure tab first."}

    gl   = json.loads(GITLAB_OUTPUTS_PATH.read_text())
    vars = VARS_PATH.read_text()

    cp_ip = ""
    for line in vars.splitlines():
        if line.strip().startswith("cp_ip:"):
            cp_ip = line.split(":", 1)[1].strip().strip('"')

    cp_user = ""
    if INVENTORY_PATH.exists():
        for line in INVENTORY_PATH.read_text().splitlines():
            if "ansible_user=" in line and "[" not in line:
                for part in line.split():
                    if part.startswith("ansible_user="):
                        cp_user = part.split("=", 1)[1]
                        break
                break

    # BUG-04 fix: read worker IP from gitlab-vars.yml — must match OAuth callback
    worker_ip = cp_ip
    if GITLAB_VARS_PATH.exists():
        for line in GITLAB_VARS_PATH.read_text().splitlines():
            if "jupyterhub_callback_url" in line:
                m = re.search(r'http://([^:]+):', line)
                if m:
                    worker_ip = m.group(1)
                    break

    crypt_key = secrets.token_hex(32)
    access_node_ip = worker_ip

    content = (
        f"# Generated by k8s-launcher — do not edit manually\n\n"
        f"jhub_gitlab_url:          \"{gl['gitlab_url']}\"\n"
        f"jhub_oauth_client_id:     \"{gl['oauth_client_id']}\"\n"
        f"jhub_oauth_client_secret: \"{gl['oauth_client_secret']}\"\n"
        f"jhub_registry_host:       \"{gl['gitlab_registry_host']}\"\n"
        f"jhub_registry_namespace:  \"{gl['registry_namespace']}\"\n"
        f"jhub_registry_pull_user:  \"{gl['registry_deploy_token_user']}\"\n"
        f"jhub_registry_pull_pass:  \"{gl['registry_deploy_token_pass']}\"\n"
        f"jhub_crypt_key:            \"{crypt_key}\"\n"
        f"jhub_access_node_ip:      \"{access_node_ip}\"\n"
        f"jhub_nodeport:             {cfg.nodeport}\n"
        f"jhub_chart_version:        \"3.3.8\"\n"
        f"jhub_namespace:            \"jhub\"\n"
        f"jhub_release_name:         \"jhub\"\n"
        f"jhub_artifacts_dir:        \"/home/{cp_user}/cluster-artifacts/jupyterhub\"\n"
        f"cp_ssh_user:               \"{cp_user}\"\n"
        f"storage_class:             \"{cfg.storage_class}\"\n"
        f"user_storage_capacity:     \"{cfg.user_storage}\"\n"
    )

    JUPYTERHUB_VARS_PATH.write_text(content)
    return {
        "status":         "ok",
        "access_url":     f"http://{access_node_ip}:{cfg.nodeport}",
    }


def _jhub_stream():
    if not INVENTORY_PATH.exists():
        yield "data: __ERROR__:no_inventory\n\n"
        return
    if not JUPYTERHUB_VARS_PATH.exists():
        yield "data: __ERROR__:no_jhub_vars — run /api/jupyterhub/configure first\n\n"
        return

    process = subprocess.Popen(
        ["ansible-playbook",
         "-i", str(INVENTORY_PATH),
         "site.yml",
         "--extra-vars", f"@{VARS_PATH}",
         "--extra-vars", f"@{JUPYTERHUB_VARS_PATH}"],
        cwd=str(ANSIBLE_JUPYTERHUB_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    for line in iter(process.stdout.readline, ""):
        stripped = line.rstrip()
        if stripped:
            yield f"data: {stripped}\n\n"

    process.stdout.close()
    process.wait()

    if process.returncode == 0:
        yield "data: __DONE__\n\n"
    else:
        yield f"data: __ERROR__:{process.returncode}\n\n"


@router.get("/api/jupyterhub/stream")
async def jupyterhub_deploy_stream():
    return StreamingResponse(
        _jhub_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
