---
- name: Check if this node already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Read saved join command from control plane
  slurp:
    src: "{{ artifacts_dir }}/join-command.txt"
  register: join_command_b64
  delegate_to: "{{ groups['control_plane'][0] }}"
  when: not kubelet_conf.stat.exists

- name: Run join command
  shell: "{{ join_command_b64.content | b64decode | trim }}"
  become: yes
  when: not kubelet_conf.stat.exists

- name: Label node as worker
  command: >
    kubectl label node {{ inventory_hostname | lower }}
    node-role.kubernetes.io/worker=worker --overwrite
  delegate_to: "{{ groups['control_plane'][0] }}"
  become: no
  when: not kubelet_conf.stat.exists
