"""
routes/gpu_policy.py — GPU access policy management via Kyverno ClusterPolicies.

Policy model: DEFAULT DENY
  Groups not explicitly listed in type_policies have zero GPU access.
  The admin grants access by adding a group to type_policies with an
  allowed GPU type list and an optional per-group count ceiling.

Three dynamic ClusterPolicies generated by this file:

  jupyterhub-gpu-default-deny  (NEW)
    Denies GPU pods from any group NOT listed in type_policies.
    This is the default-deny wall. Without this, unlisted groups
    would be unrestricted, which is the opposite of what we want.

  jupyterhub-gpu-types  (EXTENDED)
    One rule per group in type_policies.
    Denies pods whose GPU model is not in the group's allowed list.
    Also denies pods requesting more GPUs than the group's per-group ceiling.
    Both checks live in the same rule so they are evaluated together.

  jupyterhub-gpu-ceiling  (NEW)
    One global rule. Denies any GPU pod requesting more than
    global_max_gpu_per_pod regardless of which group it belongs to.
    This is the hard backstop against runaway resource requests.
    Default is 4. Admin sets it from the dashboard.

Static policy (NOT managed here):
  require-gpu-node-selector — lives in ansible-kyverno, never touched here.

ConfigMap schema (gpu-group-policy in jhub namespace):
  {
    "global_max_gpu_per_pod": 4,
    "type_policies": [
      {
        "gitlab_group": "phd-students",
        "allowed_gpu_types": ["NVIDIA-A2"],
        "max_gpu_per_pod": 2
      }
    ]
  }

Groups not in type_policies = no GPU access. No blocked_groups list needed.
"""

import hashlib
import json
import os
import shutil
import subprocess
import tempfile

import yaml
from flask import Blueprint, jsonify, request

from app.auth import require_auth
import app.config as config

bp = Blueprint("gpu_policy", __name__)

POLICY_CM_NAME      = "gpu-group-policy"
POLICY_CM_NS        = config.CONFIGMAP_NS

# The three dynamic policy names.
# default-deny is new. types is extended. ceiling replaces old block policy.
DEFAULT_DENY_POLICY_NAME = "jupyterhub-gpu-default-deny"
TYPES_POLICY_NAME        = "jupyterhub-gpu-types"
CEILING_POLICY_NAME      = "jupyterhub-gpu-ceiling"

# Default global ceiling when no value is set by admin.
DEFAULT_GLOBAL_MAX = 4

_KUBECTL = shutil.which("kubectl") or "/usr/local/bin/kubectl"

# Dot notation — bracket notation ["nvidia.com/gpu"] rejected by Kyverno webhook.
# PyYAML serializes these correctly: ."nvidia.com/gpu" (dot + quoted identifier).
_GPU_COUNT_EXPR   = '{{ request.object.spec.containers[0].resources.limits."nvidia.com/gpu" || \'0\' }}'
_GPU_PRODUCT_EXPR = '{{ request.object.spec.nodeSelector."nvidia.com/gpu.product" || \'\' }}'
_GROUP_LABEL_EXPR = '{{ request.object.metadata.labels."workbench/gitlab-group" || \'\' }}'


# ── kubectl helpers ────────────────────────────────────────────────────────────

def _run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def _apply_policy(policy_yaml, policy_name):
    """
    Delete then create — avoids resourceVersion conflict on Kyverno CRD objects.
    kubectl apply fails on existing ClusterPolicy CRDs with resourceVersion conflict.
    Delete-then-create is the correct pattern for full-replace semantics.
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
        f.write(policy_yaml)
        policy_file = f.name
    try:
        _run([_KUBECTL, "delete", "clusterpolicy", policy_name, "--ignore-not-found"])
        r = _run([_KUBECTL, "create", "-f", policy_file])
        return r.returncode == 0, r.stdout + r.stderr
    finally:
        os.unlink(policy_file)


def _delete_policy(policy_name):
    """Remove a policy that is no longer needed (e.g. no groups defined)."""
    _run([_KUBECTL, "delete", "clusterpolicy", policy_name, "--ignore-not-found"])


# ── ConfigMap read/write ───────────────────────────────────────────────────────

def _read_policy():
    """
    Read the gpu-group-policy ConfigMap.
    Returns the canonical schema with safe defaults on any failure.
    """
    r = _run([
        _KUBECTL, "get", "configmap", POLICY_CM_NAME,
        "-n", POLICY_CM_NS, "-o", "jsonpath={.data.policy}"
    ])
    if r.returncode != 0 or not r.stdout.strip():
        return {"global_max_gpu_per_pod": DEFAULT_GLOBAL_MAX, "type_policies": []}
    try:
        data = json.loads(r.stdout.strip())
        data.setdefault("global_max_gpu_per_pod", DEFAULT_GLOBAL_MAX)
        data.setdefault("type_policies", [])
        # Migration: if old schema had blocked_groups, silently drop it.
        # The default-deny model makes blocked_groups redundant.
        data.pop("blocked_groups", None)
        return data
    except (json.JSONDecodeError, ValueError):
        return {"global_max_gpu_per_pod": DEFAULT_GLOBAL_MAX, "type_policies": []}


def _write_policy(data):
    """Write the policy data to the ConfigMap, creating it if absent."""
    json_str = json.dumps(data, indent=2)
    check = _run([_KUBECTL, "get", "configmap", POLICY_CM_NAME, "-n", POLICY_CM_NS])
    if check.returncode != 0:
        r = _run([
            _KUBECTL, "create", "configmap", POLICY_CM_NAME,
            "-n", POLICY_CM_NS, "--from-literal", "policy=" + json_str
        ])
        return r.returncode == 0, r.stdout + r.stderr
    patch = {"data": {"policy": json_str}}
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(patch, f)
        pf = f.name
    try:
        r = _run([
            _KUBECTL, "patch", "configmap", POLICY_CM_NAME,
            "-n", POLICY_CM_NS, "--type=merge", "--patch-file", pf
        ])
        return r.returncode == 0, r.stdout + r.stderr
    finally:
        os.unlink(pf)


# ── Rule name helper ───────────────────────────────────────────────────────────

def _rule_name(prefix, gitlab_group):
    """
    Generate a stable, Kubernetes-safe rule name from a group path.
    Uses an MD5 suffix to prevent collisions between similar group names.
    """
    safe  = gitlab_group.replace("/", "-").replace("_", "-").lower()
    token = hashlib.md5(gitlab_group.encode()).hexdigest()[:6]
    return f"{prefix}-{safe}-{token}"


# ── Policy builders ────────────────────────────────────────────────────────────

def _build_default_deny_policy(type_policies):
    """
    Build jupyterhub-gpu-default-deny.

    This is the default-deny wall. It denies GPU pods from any group that
    is NOT explicitly listed in type_policies.

    Logic: if a pod requests GPU AND its group label is NOT IN the allowed
    group list, deny it. Groups in type_policies pass through this gate and
    are then checked by jupyterhub-gpu-types.

    If no groups are defined yet, this policy denies ALL GPU pods — which is
    the correct default state before any group is granted access.
    """
    # Build the list of allowed groups from type_policies.
    # Empty list means nobody is allowed — deny everything.
    # Only groups with a non-empty allowed_gpu_types list are treated as allowed.
    # A group with an empty list would bypass the default-deny wall but have no
    # type policy, giving it unrestricted GPU type access — the opposite of intended.
    allowed_groups = [
        tp["gitlab_group"]
        for tp in type_policies
        if tp.get("gitlab_group") and tp.get("allowed_gpu_types")
    ]

    policy = {
        "apiVersion": "kyverno.io/v1",
        "kind":       "ClusterPolicy",
        "metadata": {
            "name": DEFAULT_DENY_POLICY_NAME,
            "annotations": {
                "policies.kyverno.io/title":
                    "JupyterHub GPU Default Deny",
                "policies.kyverno.io/description": (
                    "Default-deny wall for GPU access. "
                    "Denies GPU pods from groups not explicitly granted access. "
                    "Allowed groups: " + (", ".join(allowed_groups) if allowed_groups else "none")
                )
            }
        },
        "spec": {
            "validationFailureAction": "Enforce",
            "background":             False,
            "rules": [{
                "name": "deny-unlisted-groups",
                "match": {
                    "any": [{
                        "resources": {
                            "kinds":      ["Pod"],
                            "namespaces": [POLICY_CM_NS],
                            "operations": ["CREATE"],
                        }
                    }]
                },
                "preconditions": {
                    "all": [{
                        # Only fire this rule when the pod requests at least 1 GPU.
                        # CPU pods from any group are completely unaffected.
                        "key":      _GPU_COUNT_EXPR,
                        "operator": "GreaterThan",
                        "value":    "0"
                    }]
                },
                "validate": {
                    "message": (
                        "Your group does not have GPU access. "
                        "Contact your administrator to request GPU permissions."
                    ),
                    "deny": {
                        "conditions": {
                            "all": [{
                                # Deny if the pod's group label is NOT in the allowed list.
                                # An empty allowed_groups list means deny everyone.
                                "key":      _GROUP_LABEL_EXPR,
                                "operator": "NotIn",
                                "value":    allowed_groups if allowed_groups else ["__nobody__"]
                            }]
                        }
                    }
                }
            }]
        }
    }
    return yaml.dump(policy, default_flow_style=False, allow_unicode=True)


def _build_types_policy(type_policies):
    """
    Build jupyterhub-gpu-types.

    One rule per group. Each rule checks two things:
      1. GPU type: nodeSelector.nvidia.com/gpu.product must be in allowed_types
      2. GPU count: nvidia.com/gpu must be <= max_gpu_per_pod for this group

    Both checks use deny conditions so they are evaluated independently.
    A pod fails if EITHER condition is violated.

    Groups with no allowed_gpu_types are skipped — they are handled by
    the default-deny policy which already blocks them.
    """
    rules = []
    for tp in type_policies:
        grp           = tp.get("gitlab_group", "")
        allowed_types = tp.get("allowed_gpu_types", [])
        max_gpu       = tp.get("max_gpu_per_pod")

        if not grp or not allowed_types:
            continue

        deny_conditions = []

        # Condition 1: GPU type must be in the allowed list for this group.
        deny_conditions.append({
            "key":      _GPU_PRODUCT_EXPR,
            "operator": "NotIn",
            "value":    allowed_types
        })

        # Condition 2 (optional): GPU count must not exceed per-group ceiling.
        # Only added if the admin set a per-group max. The global ceiling policy
        # handles the absolute backstop, so this is an optional tighter limit.
        if max_gpu and int(max_gpu) > 0:
            deny_conditions.append({
                "key":      _GPU_COUNT_EXPR,
                "operator": "GreaterThan",
                "value":    str(int(max_gpu))
            })

        rule = {
            "name": _rule_name("gpu-type", grp),
            "match": {
                "any": [{
                    "resources": {
                        "kinds":      ["Pod"],
                        "namespaces": [POLICY_CM_NS],
                        "operations": ["CREATE"],
                        "selector": {
                            "matchLabels": {
                                "workbench/gitlab-group": grp
                            }
                        }
                    }
                }]
            },
            "preconditions": {
                "all": [{
                    "key":      _GPU_COUNT_EXPR,
                    "operator": "GreaterThan",
                    "value":    "0"
                }]
            },
            "validate": {
                "message": (
                    f"Group '{grp}' may only use GPU type(s): "
                    f"{', '.join(allowed_types)}"
                    + (f" and may request at most {max_gpu} GPU(s) per session." if max_gpu else ".")
                ),
                "deny": {
                    "conditions": {
                        # ANY of these conditions failing denies the pod.
                        # Type mismatch OR count exceeded both result in denial.
                        "any": deny_conditions
                    }
                }
            }
        }
        rules.append(rule)

    if not rules:
        return None

    policy = {
        "apiVersion": "kyverno.io/v1",
        "kind":       "ClusterPolicy",
        "metadata": {
            "name": TYPES_POLICY_NAME,
            "annotations": {
                "policies.kyverno.io/title":
                    "JupyterHub GPU Type and Count Policy",
                "policies.kyverno.io/description":
                    "Enforces GPU type allowlists and per-group count ceilings."
            }
        },
        "spec": {
            "validationFailureAction": "Enforce",
            "background":             False,
            "rules":                  rules
        }
    }
    return yaml.dump(policy, default_flow_style=False, allow_unicode=True)


def _build_ceiling_policy(global_max):
    """
    Build jupyterhub-gpu-ceiling.

    One global rule. Denies any GPU pod in the jhub namespace that requests
    more than global_max_gpu_per_pod GPUs, regardless of group.

    This is the hard backstop against runaway requests. Even if an admin
    creates a profile with gpu_count=8 by mistake, this policy blocks it.
    The ceiling is admin-configurable from the dashboard (default: 4).

    This policy fires AFTER the default-deny and types policies, so it only
    needs to check the count — type and access are already validated.
    """
    policy = {
        "apiVersion": "kyverno.io/v1",
        "kind":       "ClusterPolicy",
        "metadata": {
            "name": CEILING_POLICY_NAME,
            "annotations": {
                "policies.kyverno.io/title":
                    "JupyterHub GPU Global Ceiling",
                "policies.kyverno.io/description": (
                    f"Hard ceiling: no pod in the jhub namespace may request "
                    f"more than {global_max} GPU(s). "
                    f"Admin-configurable from the workbench-admin dashboard."
                )
            }
        },
        "spec": {
            "validationFailureAction": "Enforce",
            "background":             False,
            "rules": [{
                "name": "deny-above-global-ceiling",
                "match": {
                    "any": [{
                        "resources": {
                            "kinds":      ["Pod"],
                            "namespaces": [POLICY_CM_NS],
                            "operations": ["CREATE"],
                        }
                    }]
                },
                "preconditions": {
                    "all": [{
                        "key":      _GPU_COUNT_EXPR,
                        "operator": "GreaterThan",
                        "value":    "0"
                    }]
                },
                "validate": {
                    "message": (
                        f"GPU request exceeds the cluster ceiling of {global_max} GPU(s) per session. "
                        f"Contact your administrator to request an increase."
                    ),
                    "deny": {
                        "conditions": {
                            "all": [{
                                "key":      _GPU_COUNT_EXPR,
                                "operator": "GreaterThan",
                                "value":    str(int(global_max))
                            }]
                        }
                    }
                }
            }]
        }
    }
    return yaml.dump(policy, default_flow_style=False, allow_unicode=True)


# ── Endpoints ──────────────────────────────────────────────────────────────────

@bp.route("/api/gpu-policy")
@require_auth
def api_get_policy():
    return jsonify(_read_policy())


@bp.route("/api/gpu-policy", methods=["POST"])
@require_auth
def api_set_policy():
    data          = request.json or {}
    type_policies = data.get("type_policies", [])

    # Parse and validate global ceiling — guard against non-integer input.
    try:
        global_max = int(data.get("global_max_gpu_per_pod", DEFAULT_GLOBAL_MAX))
    except (TypeError, ValueError):
        return jsonify({
            "success": False,
            "error": (
                f"global_max_gpu_per_pod must be an integer. "
                f"Got: {data.get('global_max_gpu_per_pod')!r}"
            )
        }), 400

    if global_max < 1 or global_max > 32:
        return jsonify({
            "success": False,
            "error": "global_max_gpu_per_pod must be between 1 and 32"
        }), 400

    # Validate each type policy entry.
    seen = set()
    for tp in type_policies:
        grp = str(tp.get("gitlab_group", "")).strip()
        if not grp:
            return jsonify({"success": False,
                            "error": "Each type policy needs a gitlab_group"}), 400
        if grp in seen:
            return jsonify({"success": False,
                            "error": f"Duplicate group '{grp}' in type policies"}), 400
        if not isinstance(tp.get("allowed_gpu_types", []), list):
            return jsonify({"success": False,
                            "error": f"allowed_gpu_types must be a list for '{grp}'"}), 400
        if not tp.get("allowed_gpu_types"):
            return jsonify({
                "success": False,
                "error": (
                    f"allowed_gpu_types cannot be empty for group '{grp}'. "
                    f"Specify at least one GPU type, or remove this group entry entirely."
                )
            }), 400

        # Validate per-group max: must be absent/null OR an integer >= 1.
        # Values of 0 or -1 are rejected — they imply "no limit" in the builder
        # but look like a real ceiling in the UI, which misleads the admin.
        per_max = tp.get("max_gpu_per_pod")
        if per_max is not None:
            try:
                per_max = int(per_max)
            except (TypeError, ValueError):
                return jsonify({
                    "success": False,
                    "error": (
                        f"max_gpu_per_pod for group '{grp}' must be an integer. "
                        f"Got: {tp.get('max_gpu_per_pod')!r}"
                    )
                }), 400
            if per_max < 1:
                return jsonify({
                    "success": False,
                    "error": (
                        f"max_gpu_per_pod for group '{grp}' must be >= 1. "
                        f"To remove the per-group ceiling, leave the field empty."
                    )
                }), 400
            if per_max > global_max:
                return jsonify({
                    "success": False,
                    "error": (
                        f"Group '{grp}' max_gpu_per_pod ({per_max}) "
                        f"exceeds global_max_gpu_per_pod ({global_max}). "
                        f"Per-group ceiling cannot exceed the global ceiling."
                    )
                }), 400
            tp["max_gpu_per_pod"] = per_max

        seen.add(grp)
        tp["gitlab_group"] = grp

    # Write the clean schema to the ConfigMap.
    clean_data = {
        "global_max_gpu_per_pod": global_max,
        "type_policies":          type_policies,
    }
    ok, detail = _write_policy(clean_data)
    if not ok:
        return jsonify({"success": False,
                        "error": "Failed to save to ConfigMap",
                        "detail": detail}), 500

    # Generate and apply all three dynamic policies.
    results = {}

    # Migration cleanup: delete legacy policy names from the old block-list model.
    # If these do not exist, --ignore-not-found makes this a no-op.
    # Without this, old policies can continue denying pods even after the new
    # model is saved, because Kyverno keeps enforcing whatever is in the cluster.
    for legacy_name in ["jupyterhub-gpu-block"]:
        _delete_policy(legacy_name)

    # Policy 1: default-deny wall (always applied, even with empty type_policies).
    deny_yaml = _build_default_deny_policy(type_policies)
    ok, detail = _apply_policy(deny_yaml, DEFAULT_DENY_POLICY_NAME)
    results["default_deny"] = "applied" if ok else f"failed: {detail}"

    # Policy 2: per-group type and count rules (removed if no groups defined).
    types_yaml = _build_types_policy(type_policies)
    if types_yaml:
        ok, detail = _apply_policy(types_yaml, TYPES_POLICY_NAME)
        results["types"] = "applied" if ok else f"failed: {detail}"
    else:
        _delete_policy(TYPES_POLICY_NAME)
        results["types"] = "removed (no groups with allowed types)"

    # Policy 3: global ceiling backstop (always applied).
    ceiling_yaml = _build_ceiling_policy(global_max)
    ok, detail = _apply_policy(ceiling_yaml, CEILING_POLICY_NAME)
    results["ceiling"] = "applied" if ok else f"failed: {detail}"

    if any("failed" in v for v in results.values()):
        return jsonify({
            "success": False,
            "error":   "One or more policies failed to apply",
            "detail":  results
        }), 500

    allowed_count = len([t for t in type_policies if t.get("allowed_gpu_types")])
    return jsonify({
        "success": True,
        "message": (
            f"{allowed_count} group(s) with GPU access · "
            f"Global ceiling: {global_max} GPU(s) per session."
        ),
        "detail": results
    })


@bp.route("/api/gpu-policy/status")
@require_auth
def api_policy_status():
    """Check existence and readiness of all three dynamic policies."""
    def _check(name):
        r = _run([_KUBECTL, "get", "clusterpolicy", name, "--no-headers"])
        if r.returncode != 0:
            return {"exists": False, "ready": False}
        rr = _run([_KUBECTL, "get", "clusterpolicy", name,
                   "-o", "jsonpath={.status.ready}"])
        return {
            "exists": True,
            "ready":  rr.returncode == 0 and rr.stdout.strip().lower() == "true"
        }

    return jsonify({
        "default_deny_policy": _check(DEFAULT_DENY_POLICY_NAME),
        "types_policy":        _check(TYPES_POLICY_NAME),
        "ceiling_policy":      _check(CEILING_POLICY_NAME),
    })


@bp.route("/api/gpu-policy/available-groups")
@require_auth
def api_available_groups():
    """Return all GitLab groups that have at least one profile defined."""
    r = _run([
        _KUBECTL, "get", "configmap", config.CONFIGMAP_NAME,
        "-n", config.CONFIGMAP_NS,
        "-o", r"jsonpath={.data.profiles\.json}"
    ])
    if r.returncode != 0:
        return jsonify({"groups": [],
                        "error": "Could not read jupyterhub-profiles ConfigMap"})
    raw = r.stdout.strip()
    if not raw:
        return jsonify({"groups": []})
    try:
        profiles = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return jsonify({"groups": [], "error": "profiles.json is not valid JSON"})
    seen = []
    for p in profiles:
        g = str(p.get("gitlab_group", "")).strip()
        if g and g not in seen:
            seen.append(g)
    return jsonify({"groups": seen})
