all:
  children:
    gitlab:
      hosts:
        ansiblegitlab:
          ansible_host: "REPLACE_WITH_GITLAB_VM_IP"
          ansible_user: "REPLACE_WITH_SSH_USER"
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
          ansible_python_interpreter: /usr/bin/python3
